filebeat.inputs:

- type: log
  enabled: false
  paths:
    - /var/log/nginx/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

setup.kibana:
  host: "http://{{ kibana_id_addr }}:5601"
  username: "elastic"
  password: "{{ elastic_password }}"

output.elasticsearch:
  hosts: ["{{ ES_ip_addr }}:9200"]
  protocol: "http"
  username: "elastic"
  password: "{{ elastic_password }}"