---

- name: Create ES volume
  docker_volume:
    name: esdata
    driver: local

- name: Create a network
  docker_network:
    name: "{{ network_name }}"

- name: Start elastic search container
  docker_container:
    name: "{{ ES_cont_name }}"
    image: "{{ ES_image }}"
    env:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
    volumes:
    - "esdata:/usr/share/elasticsearch/data"
    ports:
    - 9200:9200
    networks:
    - name: "{{ network_name }}"
    state: started
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"

# - debug:
#     msg: >
#       Users have to be configured manually. Enable and set the password for the default users with:
#       `docker exec -it {{ elasticsearch_hostname }} /bin/bash -c "elasticsearch-setup-passwords auto"`
#       Then edit the `vaul.yml` file and copy the password values to the expected variable.