---
- name: Download and install .deb-package
  apt:
    deb: https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v{{ nodeexporter_version }}/prometheus-nginxlog-exporter_{{ nodeexporter_version }}_linux_amd64.deb
  notify:
    - nginxlog-exporter

- name: install IPTABLES
  apt:
    name: iptables
    state: present

- name: Security Settings For Debian
  block:
    - name: Allow TCP Ports
      iptables:
        chain: INPUT
        rule_num: '1'
        action: insert
        protocol: tcp
        jump: ACCEPT
        destination_port: "4040"
      
- name: Change nginx *.log files permissions
  file:
    path: "/var/log/nginx/{{ item }}"
    mode: 0644
  loop:
    - 'access.log'
    - 'error.log'
  notify:
    - nginx-server   

- name: Create the nginxlog_exporter configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - nginx-server

- name: Create the nginxlog_exporter configuration file
  template:
    src: nginxlog_exporter_configuration.hcl.j2
    dest: /etc/prometheus-nginxlog-exporter.hcl
    mode: 0644